version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
