services:
  - type: web
    name: realtime-chat-app
    env: docker
    repo: https://github.com/Parsa132000/realtime-chat.git
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /ping
    dockerfilePath: ./Dockerfile  # ✅ good
    autoDeploy: true              # ✅ optional: ensure auto-deploy from GitHub
    envVars:
      - key: REDIS_HOST
        value: chat-redis         # ✅ make sure this matches your redis service name

  - type: redis
    name: chat-redis
    plan: free
